name: build

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v7
        with:
          version: latest
          no-cache: true
      - name: Install dependencies
        run: npm install -g terser
      - name: Build wasm-aes
        run: node build.js
      - name: Test
        run: |
          curl https://cdn.jsdelivr.net/npm/aes-js@3/index.min.js --output aes-js.min.js
          curl https://cdn.jsdelivr.net/npm/crypto-js@3/crypto-js.min.js --output crypto-js.min.js
          node test.js
      - name: Benchmark
        run: node benchmark.js
      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: wasm-aes
          path: dist/
